[package]
name              = "nevelio-module-oauth2"
version.workspace     = true
edition.workspace     = true
authors.workspace     = true
license.workspace     = true
description           = "OAuth2 and OpenID Connect security testing module for the Nevelio API security scanner"
homepage.workspace    = true
repository.workspace  = true
keywords.workspace    = true
categories.workspace  = true
readme.workspace      = true

[dependencies]
nevelio-core          = { path = "../../core", version = "0.1" }
async-trait.workspace = true
anyhow.workspace      = true
tracing.workspace     = true
tokio.workspace       = true
reqwest.workspace     = true
serde.workspace       = true
serde_json.workspace  = true
