use anyhow::{Context, Result};
use colored::Colorize;
use nevelio_core::types::{Finding, Severity};
use nevelio_reporting::ScanReport;
use std::collections::HashSet;
use std::time::Duration;

use crate::args::LinearIssueArgs;
use crate::notify::severity_meets_threshold;

pub(super) async fn handle_linear(report: &ScanReport, args: LinearIssueArgs) -> Result<()> {
    let token = args
        .token
        .or_else(|| std::env::var("LINEAR_API_KEY").ok())
        .context("Clé API Linear requise. Utilisez --token ou la variable LINEAR_API_KEY.")?;

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(15))
        .build()?;

    let to_create: Vec<&Finding> = report
        .findings
        .iter()
        .filter(|f| severity_meets_threshold(&f.severity, &args.min_severity))
        .collect();

    if to_create.is_empty() {
        println!("  Aucun finding au-dessus du seuil. Aucun ticket Linear créé.");
        return Ok(());
    }

    let label_id = if let Some(ref label_name) = args.label {
        resolve_linear_label(&client, &token, label_name)
            .await
            .ok()
            .flatten()
    } else {
        None
    };

    let existing_titles = fetch_linear_issue_titles(&client, &token, &args.team).await?;
    let mut created = 0u32;
    let mut skipped = 0u32;

    for finding in &to_create {
        let title = format!("[Nevelio] {} — {}", finding.title, finding.module);
        if existing_titles.contains(&title) {
            skipped += 1;
            continue;
        }

        let description = format!(
            "## Security Finding\n\n\
             **Module:** {module}\n**Endpoint:** {ep}\n**Method:** {method}\n\
             **Severity:** {sev:?}\n**CVSS:** {cvss:.1}\n\n\
             ### Description\n{desc}\n\n### Recommendation\n{rec}\n\n\
             {cwe}---\n*Generated by Nevelio v{ver} | Target: {target}*",
            module = finding.module,
            ep = finding.endpoint,
            method = finding.method,
            sev = finding.severity,
            cvss = finding.cvss_score,
            desc = finding.description,
            rec = finding.recommendation,
            cwe = finding
                .cwe
                .as_deref()
                .map(|c| format!("**CWE:** {}\n\n", c))
                .unwrap_or_default(),
            ver = env!("CARGO_PKG_VERSION"),
            target = report.target,
        );

        let priority = linear_priority_for_sev(&finding.severity);

        let mut variables = serde_json::json!({
            "teamId": args.team, "title": title,
            "description": description, "priority": priority,
        });
        if let Some(ref pid) = args.project {
            variables["projectId"] = serde_json::json!(pid);
        }
        if let Some(ref lid) = label_id {
            variables["labelIds"] = serde_json::json!([lid]);
        }

        let mutation = r#"
            mutation CreateIssue($teamId: String!, $title: String!, $description: String, $priority: Int, $projectId: String, $labelIds: [String!]) {
                issueCreate(input: {
                    teamId: $teamId, title: $title, description: $description,
                    priority: $priority, projectId: $projectId, labelIds: $labelIds
                }) { success  issue { id url } }
            }
        "#;

        let resp = client
            .post("https://api.linear.app/graphql")
            .header("Authorization", &token)
            .header("Content-Type", "application/json")
            .json(&serde_json::json!({ "query": mutation, "variables": variables }))
            .send()
            .await
            .context("Erreur appel Linear API")?;

        let body: serde_json::Value = resp.json().await?;
        if body["data"]["issueCreate"]["success"]
            .as_bool()
            .unwrap_or(false)
        {
            let url = body["data"]["issueCreate"]["issue"]["url"]
                .as_str()
                .unwrap_or("");
            println!("  {} Linear issue créé : {}", "✓".green(), url);
            created += 1;
        } else if let Some(errors) = body["errors"].as_array() {
            let msg = errors
                .first()
                .and_then(|e| e["message"].as_str())
                .unwrap_or("unknown");
            eprintln!("  ✗ Erreur Linear : {}", msg);
        }

        tokio::time::sleep(Duration::from_millis(300)).await;
    }

    println!(
        "\n  Bilan : {} issue(s) créé(s), {} ignoré(s) (déjà existants).",
        created, skipped
    );
    Ok(())
}

async fn fetch_linear_issue_titles(
    client: &reqwest::Client,
    token: &str,
    team_id: &str,
) -> Result<HashSet<String>> {
    let query = r#"
        query TeamIssues($teamId: String!) {
            team(id: $teamId) {
                issues(filter: { title: { startsWith: "[Nevelio]" } }) {
                    nodes { title }
                }
            }
        }
    "#;

    let resp = client
        .post("https://api.linear.app/graphql")
        .header("Authorization", token)
        .header("Content-Type", "application/json")
        .json(&serde_json::json!({ "query": query, "variables": { "teamId": team_id } }))
        .send()
        .await?;

    let body: serde_json::Value = resp.json().await?;
    let titles = body["data"]["team"]["issues"]["nodes"]
        .as_array()
        .unwrap_or(&vec![])
        .iter()
        .filter_map(|n| n["title"].as_str().map(String::from))
        .collect();

    Ok(titles)
}

async fn resolve_linear_label(
    client: &reqwest::Client,
    token: &str,
    label_name: &str,
) -> Result<Option<String>> {
    let query = r#"query { issueLabels { nodes { id name } } }"#;
    let resp = client
        .post("https://api.linear.app/graphql")
        .header("Authorization", token)
        .header("Content-Type", "application/json")
        .json(&serde_json::json!({ "query": query }))
        .send()
        .await?;

    let body: serde_json::Value = resp.json().await?;
    let id = body["data"]["issueLabels"]["nodes"]
        .as_array()
        .unwrap_or(&vec![])
        .iter()
        .find(|n| {
            n["name"]
                .as_str()
                .map(|s| s.eq_ignore_ascii_case(label_name))
                .unwrap_or(false)
        })
        .and_then(|n| n["id"].as_str().map(String::from));

    Ok(id)
}

fn linear_priority_for_sev(sev: &Severity) -> u8 {
    match sev {
        Severity::Critical => 1,
        Severity::High => 2,
        Severity::Medium => 3,
        Severity::Low | Severity::Informative => 4,
    }
}
