use anyhow::{Context, Result};
use chrono::Utc;
use std::collections::HashMap;
use std::path::Path;
use tera::Tera;

use crate::report_types::ScanReport;

const TEMPLATE: &str = include_str!("../templates/report.html");
const CSS: &str = include_str!("../templates/report.css");
const JS: &str = include_str!("../templates/report.js");

fn i18n_labels(locale: &str) -> HashMap<&'static str, &'static str> {
    match locale {
        "fr" => [
            ("title",          "Nevelio — Rapport de Sécurité API"),
            ("toggle_theme",   "Basculer le thème"),
            ("target",         "Cible"),
            ("profile",        "Profil"),
            ("started",        "Démarré"),
            ("duration",       "Durée"),
            ("total",          "Total"),
            ("critical",       "Critical"),
            ("high",           "High"),
            ("medium",         "Medium"),
            ("low",            "Low"),
            ("informative",    "Informative"),
            ("filter",         "Filtrer :"),
            ("all",            "Tous"),
            ("search",         "Rechercher..."),
            ("description",    "Description"),
            ("recommendation", "Recommandation"),
            ("proof",          "Preuve"),
            ("references",     "Références"),
            ("no_findings",    "✓ Aucun finding détecté"),
            ("generated_by",   "Généré par"),
            ("footer_suffix",  "Outil de Pentest API · Usage autorisé uniquement sur systèmes avec autorisation explicite"),
        ],
        "es" => [
            ("title",          "Nevelio — Informe de Seguridad de API"),
            ("toggle_theme",   "Cambiar tema"),
            ("target",         "Objetivo"),
            ("profile",        "Perfil"),
            ("started",        "Iniciado"),
            ("duration",       "Duración"),
            ("total",          "Total"),
            ("critical",       "Crítico"),
            ("high",           "Alto"),
            ("medium",         "Medio"),
            ("low",            "Bajo"),
            ("informative",    "Informativo"),
            ("filter",         "Filtrar:"),
            ("all",            "Todos"),
            ("search",         "Buscar..."),
            ("description",    "Descripción"),
            ("recommendation", "Recomendación"),
            ("proof",          "Evidencia"),
            ("references",     "Referencias"),
            ("no_findings",    "✓ No se detectaron hallazgos"),
            ("generated_by",   "Generado por"),
            ("footer_suffix",  "Herramienta de Pentest de APIs · Solo uso autorizado en sistemas con permiso explícito"),
        ],
        _ => [  // "en" default
            ("title",          "Nevelio — API Security Report"),
            ("toggle_theme",   "Toggle theme"),
            ("target",         "Target"),
            ("profile",        "Profile"),
            ("started",        "Started"),
            ("duration",       "Duration"),
            ("total",          "Total"),
            ("critical",       "Critical"),
            ("high",           "High"),
            ("medium",         "Medium"),
            ("low",            "Low"),
            ("informative",    "Informative"),
            ("filter",         "Filter:"),
            ("all",            "All"),
            ("search",         "Search..."),
            ("description",    "Description"),
            ("recommendation", "Recommendation"),
            ("proof",          "Proof"),
            ("references",     "References"),
            ("no_findings",    "✓ No findings detected"),
            ("generated_by",   "Generated by"),
            ("footer_suffix",  "API Pentest Tool · Authorized use only on systems with explicit permission"),
        ],
    }
    .into_iter()
    .collect()
}

pub struct HtmlReporter;

impl HtmlReporter {
    pub fn generate(report: &ScanReport) -> Result<String> {
        let mut tera = Tera::default();
        tera.add_raw_template("report.css", CSS)
            .context("Failed to load CSS template")?;
        tera.add_raw_template("report.js", JS)
            .context("Failed to load JS template")?;
        tera.add_raw_template("report.html", TEMPLATE)
            .context("Failed to load HTML template")?;

        let labels = i18n_labels(&report.locale);

        let mut ctx = tera::Context::new();
        ctx.insert("scan", &serde_json::to_value(report)?);
        ctx.insert("generated_at", &Utc::now().format("%Y-%m-%d %H:%M UTC").to_string());
        ctx.insert("i18n", &labels);
        ctx.insert("version", env!("CARGO_PKG_VERSION"));

        tera.render("report.html", &ctx)
            .context("Failed to render HTML report")
    }

    pub fn write_to_file(report: &ScanReport, path: &Path) -> Result<()> {
        let html = Self::generate(report)?;
        std::fs::write(path, html)?;
        Ok(())
    }
}
