[package]
name              = "nevelio-ai"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = []
bedrock = ["dep:hmac", "dep:sha2", "dep:chrono"]

[dependencies]
nevelio-config = { path = "../nevelio-config", version = "0.1" }
serde          = { workspace = true }
serde_json     = { workspace = true }
anyhow         = { workspace = true }
reqwest        = { workspace = true }
tokio          = { workspace = true }
async-trait    = { workspace = true }
tracing        = { workspace = true }
rust-i18n      = { workspace = true }
hmac           = { workspace = true, optional = true }
sha2           = { workspace = true, optional = true }
chrono         = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true }
