use anyhow::{Context, Result};
use nevelio_core::types::{Finding, Severity};
use nevelio_reporting::ScanReport;
use std::time::Duration;

#[allow(clippy::too_many_arguments)]
pub(super) async fn send_email(
    smtp_addr: &str,
    smtp_user: Option<&str>,
    smtp_pass: Option<&str>,
    from: &str,
    to: &str,
    report: &ScanReport,
    findings: &[&Finding],
    summary: &str,
) -> Result<()> {
    let critical = findings.iter().filter(|f| matches!(f.severity, Severity::Critical)).count();
    let high     = findings.iter().filter(|f| matches!(f.severity, Severity::High)).count();

    let rows: String = findings.iter().take(20).map(|f| {
        format!(
            "<tr><td>{:?}</td><td>{}</td><td>{}</td><td>{}</td></tr>",
            f.severity, f.module, f.endpoint, f.title
        )
    }).collect();

    let html_body = format!(
        r#"<!DOCTYPE html><html><body>
<h2>Nevelio Security Report — {target}</h2>
<p><b>Summary:</b> {total} finding(s) | Critical: {crit} | High: {high}</p>
<p><b>Scan profile:</b> {profile} | Duration: {dur:.0}s</p>
<table border="1" cellpadding="4" style="border-collapse:collapse;font-family:monospace">
<tr><th>Severity</th><th>Module</th><th>Endpoint</th><th>Title</th></tr>
{rows}
</table>
{more}
<hr><small>Generated by Nevelio v{ver}</small>
</body></html>"#,
        target  = report.target,
        total   = findings.len(),
        crit    = critical,
        high    = high,
        profile = report.profile,
        dur     = report.duration_secs,
        rows    = rows,
        more    = if findings.len() > 20 {
            format!("<p><i>...and {} more findings (see findings.json)</i></p>", findings.len() - 20)
        } else { String::new() },
        ver     = env!("CARGO_PKG_VERSION"),
    );

    let msg = format!(
        "From: {from}\r\nTo: {to}\r\nSubject: {summary}\r\n\
         MIME-Version: 1.0\r\nContent-Type: text/html; charset=UTF-8\r\n\r\n{html_body}"
    );

    let (host, port_str) = smtp_addr.rsplit_once(':').unwrap_or((smtp_addr, "587"));
    let port: u16 = port_str.parse().unwrap_or(587);

    use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader};
    use tokio::net::TcpStream;

    let stream = tokio::time::timeout(
        Duration::from_secs(15),
        TcpStream::connect((host, port)),
    ).await.context("SMTP connection timeout")?.context("SMTP connection failed")?;

    let (reader_half, mut writer) = stream.into_split();
    let mut reader = BufReader::new(reader_half);

    smtp_readline(&mut reader).await?;

    writer.write_all(b"EHLO nevelio\r\n").await?;
    loop {
        let l = smtp_readline(&mut reader).await?;
        if l.len() < 4 || !l.starts_with("250-") { break; }
    }

    if let (Some(user), Some(pass)) = (smtp_user, smtp_pass) {
        use base64::Engine;
        let b64 = base64::engine::general_purpose::STANDARD;

        writer.write_all(b"AUTH LOGIN\r\n").await?;
        smtp_readline(&mut reader).await?;

        writer.write_all(format!("{}\r\n", b64.encode(user)).as_bytes()).await?;
        smtp_readline(&mut reader).await?;

        writer.write_all(format!("{}\r\n", b64.encode(pass)).as_bytes()).await?;
        let auth_resp = smtp_readline(&mut reader).await?;
        if !auth_resp.starts_with("235") {
            anyhow::bail!("SMTP auth failed: {}", auth_resp.trim());
        }
    }

    writer.write_all(format!("MAIL FROM:<{}>\r\n", from).as_bytes()).await?;
    smtp_readline(&mut reader).await?;

    writer.write_all(format!("RCPT TO:<{}>\r\n", to).as_bytes()).await?;
    smtp_readline(&mut reader).await?;

    writer.write_all(b"DATA\r\n").await?;
    smtp_readline(&mut reader).await?;

    writer.write_all(msg.as_bytes()).await?;
    writer.write_all(b"\r\n.\r\n").await?;
    smtp_readline(&mut reader).await?;

    writer.write_all(b"QUIT\r\n").await?;
    Ok(())
}

async fn smtp_readline<R: tokio::io::AsyncBufRead + Unpin>(reader: &mut R) -> Result<String> {
    let mut line = String::new();
    tokio::io::AsyncBufReadExt::read_line(reader, &mut line).await?;
    Ok(line)
}
